version: 2
updates:
  # For JavaScript (npm) dependencies
  - package-ecosystem: "npm"
    directory: "/"                # Update if your package.json is in a subfolder
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    assignees:
      - "Fadil369"

  # For GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"                # Location of .github/workflows
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "actions"
    assignees:
      - "Fadil369"

  # For Dockerfile dependencies (if present)
  - package-ecosystem: "docker"
    directory: "/"                # Update if Dockerfile is in a subfolder
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "docker"
    assignees:
      - "Fadil369"
