name = "brainsait-website"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
    { pattern = "brainsait.io/*", zone_name = "brainsait.io" },
    { pattern = "www.brainsait.io/*", zone_name = "brainsait.io" }
]

[env.staging]
vars = { ENVIRONMENT = "staging" }
route = { pattern = "staging.brainsait.io/*", zone_name = "brainsait.io" }