name = "brainsait-identity"
compatibility_date = "2024-08-01"

[env.production]
name = "brainsait-identity"
route = { pattern = "id.brainsait.io", zone_id = "your-zone-id" }

[env.preview]
name = "brainsait-identity-preview"

# Pages configuration
pages_build_output_dir = "."

# Custom domains
[[env.production.routes]]
pattern = "id.brainsait.io/*"
custom_domain = true

# Environment variables
[vars]
NODE_ENV = "production"
ENVIRONMENT = "production"
PLATFORM_NAME = "BrainSAIT Identity"
MAIN_SITE = "https://brainsait.io"
PROFILE_SITE = "https://thefadil.site"

# Build configuration
[build]
command = ""
cwd = "."
watch_dir = "."

# Asset optimization
[site]
bucket = "."

# Redirects for clean URLs
[[redirects]]
from = "/login"
to = "/"
status = 200

[[redirects]]
from = "/signin"
to = "/"
status = 301

[[redirects]]
from = "/auth"
to = "/"
status = 301

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=(), publickey-credentials-get=(self)"

[[headers]]
for = "*.html"
[headers.values]
Cache-Control = "public, max-age=3600"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
